import { 
  OCCUPATION, 
  PAYMENT_METHOD,
  PAYMENT_TYPE,
  CASH_TEMPO_PERIOD,
  KPR_TENOR_PERIOD,
  STATUS,
} from './booking-fee-constant'

export {
  OCCUPATION,
  PAYMENT_METHOD,
  PAYMENT_TYPE,
  CASH_TEMPO_PERIOD,
  KPR_TENOR_PERIOD,
  STATUS,
}